Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.cs
=> feat: enable paging for queries

Gravity/Gravity/DAL/RSAPI/RsapiDao.cs, Gravity/Gravity/DAL/RSAPI/RsapiDaoBase.cs, Gravity/Gravity/DAL/RSAPI/RsapiDocumentDao.cs, Gravity/Gravity/Gravity.csproj
=> refactor: move document RsapiDao functions to own class

.gitignore, Gravity/Gravity/Base/BaseDto.cs
Leaving removing dead code for another time.
=> refactor BaseDto class

Gravity/Gravity/DAL/RSAPI/RsapiDao.Update.cs, Gravity/Gravity/Extensions/TypeExtesions.cs
Refactoring, in the sense of rearranging. I hope to revisit the `UpdateRelativityField` logic a different time.
=> refactor: refactor RsapiDao.Update

.gitignore, Gravity/Gravity.Test.Integration/App.config, Gravity/Gravity.Test.Integration/Gravity.Test.Integration.csproj, Gravity/Gravity.Test.Integration/packages.config, developmentScripts/Build.ps1, developmentScripts/buildtools/packages.config, developmentScripts/default.ps1, developmentScripts/defaultBuildTest.ps1
Checking in build and test powershell scripts to aid in CI
=> Added developement scripts for gravity

developmentScripts/Build.ps1
Updated nuget URL to pull latest nuget.exe. I also updated the default.ps1 name to defaultBuildTest.ps1
=> Gravity with ci

Gravity/Gravity/Extensions/TypeExtensions.cs, Gravity/Gravity/Gravity.csproj
How do I tie issue #74 to this?
=> renamed extensions and cleaned up csproj file that was missing files.

Gravity/Gravity/Extensions/TypeExtensions.cs
Looks like I broke this a while ago.
=> fix: Fix Single Object field GUID detection

Gravity/Gravity.Test.Integration/Gravity.Test.Integration.csproj, Gravity/Gravity.Test.Integration/RSAPI_IntegrationTest.cs, Gravity/Gravity.Test.Integration/TestCaseDefenition.cs, Gravity/Gravity.Test.Integration/TestCaseDefinition.cs
=> Refactor: move reusable test case definitions

Gravity/Gravity.Test.Integration/RSAPI_IntegrationTest.cs, Gravity/Gravity.Test.Integration/TestCaseDefenition.cs, Gravity/Gravity.Test.Integration/TestCaseDefinition.cs, Gravity/Gravity.Test/Helpers/TestObjectHelper.cs, Gravity/Gravity.Test/TestClasses/GravityLevelOne.cs, Gravity/Gravity/Base/BaseDto.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.Insert.cs, Gravity/Gravity/Extensions/RdoExtensions.cs
I will work on the read multiple object next.  The write test does not pass but we said we would deal with that later.  Fix for issue #83
=> Adding single object tests and implemented the new read

Gravity/Gravity/Base/BaseDto.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs
Issue #56 - Added method GetFieldsGuids<T>() to BaseDto as suggested in issue comments
=> Issue #56 : Updated queries to pull only expected fields

Gravity/Gravity.Test.Integration/RSAPI_IntegrationTest.cs
=> Integration test cleanup

Gravity/Gravity.Test/TestClasses/GravityLevel2.cs, Gravity/Gravity.Test/TestClasses/GravityLevel2Child.cs, Gravity/Gravity.Test/TestClasses/GravityLevelOne.cs, Gravity/Gravity/Base/BaseDto.cs
=> remove Name from BaseDto required fields

Gravity/.editorconfig
Adds naming rules to match those in wiki
=> chore: add naming rules to editorconfig file

Gravity/Gravity.Test.Unit/RsapiDaoDeleteTests.cs, Gravity/Gravity.Test.Unit/RsapiDaoGetTests.cs, Gravity/Gravity.Test.Unit/RsapiDaoInsertTests.cs, Gravity/Gravity.Test.Unit/RsapiDaoUpdateTests.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.cs
Fixes an issue @aarongilbert123 noticed while writing file-driven unit tests
=> fix: initialize retry service in all RsapiDao constructors

Gravity/Gravity/DAL/RSAPI/RsapiDao.Get.cs
=> fix: set single object fields to null when zero value

Gravity/Gravity.Test.Unit/RsapiDaoInsertTests.cs, Gravity/Gravity.Test.Unit/RsapiDaoUpdateTests.cs, Gravity/Gravity.Test/TestClasses/GravityLevel2.cs, Gravity/Gravity.Test/TestClasses/GravityLevel3Child.cs
@Arithmomaniac Merging these tests into Feature branch so that other pull request can be approved.
=> File Field Tests Finished

Gravity/Gravity.Test.Integration/SQL_IntegrationTest.cs, Gravity/Gravity.Test/Helpers/TestObjectHelper.cs, Gravity/Gravity/DAL/SQL/SqlDao.Get.cs, Gravity/Gravity/DAL/SQL/SqlDao.cs
Provided fixes for the above Issues. Ran Integration tests and they went smoothly.
=> Fixed development SQL bugs #147 & #148

Gravity/Gravity.Test.Integration/RSAPI_IntegrationTest.File.cs
=> updated the File test to look at correct switch value for test

Gravity/Gravity.Test.Unit/RsapiDaoDeleteTests.cs, Gravity/Gravity.Test.Unit/RsapiDaoUpdateTests.cs, Gravity/Gravity/DAL/IGravityDao.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.Delete.cs, Gravity/Gravity/DAL/RSAPI/RsapiDao.Update.cs, Gravity/Gravity/DAL/SQL/SqlDao.cs
=> Bulk delete
